create table USERSDATA (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
USERNAME VARCHAR(255) NOT NULL,
MAILID VARCHAR(255) NOT NULL,
MOBILENO VARCHAR(255) NOT NULL,
GENDER VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ROLE VARCHAR(255) NOT NULL
);